networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: server-nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ../../../data/web:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ../../data/web:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ../../data/db:/var/lib/mysql
    networks:
      - inception
    restart: always