networks:
  inception:
    name: inception

volumes:
  web:
    driver_opts:
      device: /home/jkaller/data/web
      type: none
      o: bind
  db:
    driver_opts:
      device: /home/jkaller/data/db
      type: none
      o: bind

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: server-nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always

