services:
  nginx:
    build: ./requirements/nginx/.
    container_name: server-nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql